export const themePresets = {
  modern: {
    primaryColor: "#0ea5e9",
    headingFont: "Inter",
    bodyFont: "Inter",
    headingSize: 24,
    bodySize: 14,
    headingWeight: 600,
    bodyWeight: 400,
  },
  elegant: {
    primaryColor: "#8b5cf6",
    headingFont: "Georgia",
    bodyFont: "Georgia",
    headingSize: 22,
    bodySize: 16,
    headingWeight: 700,
    bodyWeight: 500,
  },
  minimal: {
    primaryColor: "#6b7280",
    headingFont: "Helvetica",
    bodyFont: "Helvetica",
    headingSize: 18,
    bodySize: 14,
    headingWeight: 500,
    bodyWeight: 400,
  },
  luxury: {
    primaryColor: "#bfa76f",
    headingFont: "Playfair Display",
    bodyFont: "Lora",
    headingSize: 28,
    bodySize: 16,
    headingWeight: 700,
    bodyWeight: 500,
  },
  streetwear: {
    primaryColor: "#ef4444",
    headingFont: "Bebas Neue",
    bodyFont: "Roboto",
    headingSize: 26,
    bodySize: 14,
    headingWeight: 700,
    bodyWeight: 400,
  },
  retro: {
    primaryColor: "#f59e0b",
    headingFont: "Courier New",
    bodyFont: "Comic Sans MS",
    headingSize: 24,
    bodySize: 15,
    headingWeight: 700,
    bodyWeight: 400,
  },
  tropical: {
    primaryColor: "#10b981",
    headingFont: "Pacifico",
    bodyFont: "Open Sans",
    headingSize: 22,
    bodySize: 15,
    headingWeight: 600,
    bodyWeight: 400,
  },
  grayscale: {
    primaryColor: "#374151",
    headingFont: "Arial",
    bodyFont: "Arial",
    headingSize: 20,
    bodySize: 13,
    headingWeight: 600,
    bodyWeight: 400,
  },
  artsy: {
    primaryColor: "#d946ef",
    headingFont: "Caveat",
    bodyFont: "Quicksand",
    headingSize: 26,
    bodySize: 15,
    headingWeight: 700,
    bodyWeight: 500,
  },
  rugged: {
    primaryColor: "#78350f",
    headingFont: "Anton",
    bodyFont: "Ubuntu",
    headingSize: 24,
    bodySize: 14,
    headingWeight: 800,
    bodyWeight: 500,
  },
};
